
name: A Basic Workflow


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "main"

jobs:
  build-app:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    #steps represent a sequence of tasks that will be executed as part of the job ##
    steps:
    # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #Runs a single command using the runners shell
      - name: Run s one-line script
        run: echo Hello world!

      - name: Run multi-line script
        run:
          echo Add other actions to build-app
          echo test, and deploy your project


  build-api:
    runs-on: windows-latest
    steps:
      - run: echo "Building Api"

  build-db:
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "Hello Windows"


  package:
    needs: [build-app, build-db]
    runs-on: macos-latest
    steps:
      - run: echo "Hello Macos"
